### ISSUE TITLE
Modificación en archivos conceptos_web_services.md y principios_codificacion_segura.md 

### ISSUE THREAD

**Issue by DMichelA** [DMichelA/proyecto_matematicas#9]
@MariaFernandaReyesLopez por favor realiza los siguientes cambios:
En el archivo conceptos_web_services.md complementa con la utilidad de un Web Service
En el archivo principios_codificacion_segura.md agrega una pequeña conclusión respecto a los principios de la codificación segura

**Comment by MariaFernandaReyesLopez** [comment]
Ya he realizado los cambios solicitados. 👍

**Comment by DMichelA** [comment]
Se verificaron los cambios que realizaste @MariaFernandaReyesLopez, gracias. En caso de requerir algún otro cambio, estaremos en contacto.
